name: 💡 Feature Request
description: Suggest a new feature or improvement for this project!
title: "[FEATURE] <Brief summary>"
labels: ["🚀 feature", "⏳ awaiting approval"]
body:
  - type: textarea
    id: summary
    attributes:
      label: ✨ Feature Summary
      description: Briefly describe the new feature or improvement.
      placeholder: "I would like to add..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: ❓ Problem to Solve
      description: What problem does this feature address? Why is it needed?
      placeholder: "Currently, the issue is..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: How do you think this should be implemented?
      placeholder: "I suggest..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Have you thought of other ways to solve this problem?
      placeholder: "Another approach could be..."
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: 📷 Screenshots (if applicable)
      description: Add screenshots or mockups to illustrate the idea.
    validations:
      required: false

  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "🔍 Have you checked for similar issues?"
      options:
        - label: "Yes, I searched and found no similar feature requests."
          required: true

  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: "📜 Contribution Guidelines"
      options:
        - label: "I have read and understood the [Contributing Guidelines](https://github.com/svyatoslavw/rndmcv-app/blob/main/CONTRIBUTING.md)"
          required: true

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: 🎯 Would you like to contribute?
      description: Not required, but we'd love your help!
      options:
        - "Yes, I am willing to submit a PR!"
        - "No, but I’d love for someone else to work on it."

  - type: markdown
    attributes:
      value: |
        🚀 Thank you for your suggestion!  
        👉 Follow me on Twitter: [@svy4tosl0v3](https://x.com/svy4tosl0v3)  
        🛠 Check out my other projects: [GitHub](https://github.com/svyatoslavw)
