import type { Metadata } from "next"
import Script from "next/script"

import "./globals.css"
import { Providers } from "./providers"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Script src="https://cdn.tailwindcss.com"></Script>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
