export { AuthPage } from "./AuthPage/AuthPage"
export { ContentPage } from "./ContentPage/ContentPage"
export { CustomizePage } from "./CustomizePage/CustomizePage"
export { HomePage } from "./HomePage/HomePage"
export { PricingPage } from "./PricingPage/PricingPage"
export { SettingsPage } from "./SettingsPage/SettingsPage"
