name: Pre-Deployment Application

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            node_modules
            **/.next
            **/node_modules
            .turbo
          key: turbo-${{ hashFiles('yarn.lock') }}-v2

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Run tests
        run: yarn turbo run test --filter=web

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            node_modules
            **/.next
            **/node_modules
            .turbo
          key: turbo-${{ hashFiles('yarn.lock') }}-v2

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Run lint
        run: yarn turbo run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            node_modules
            **/.next
            **/node_modules
            .turbo
          key: turbo-${{ hashFiles('yarn.lock') }}-v2

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Build application
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          NEXT_PUBLIC_APP_ENV: production
        run: yarn turbo run build --filter=web
