name: Turborepo CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            .pnpm-store
            node_modules
            **/.next
            **/node_modules
            .turbo
          key: turbo-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('.github/workflows/*.yml') }}

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run tests
        run: pnpm turbo run test --filter=web

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            .pnpm-store
            node_modules
            **/.next
            **/node_modules
            .turbo
          key: turbo-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('.github/workflows/*.yml') }}

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run lint
        run: pnpm turbo run lint --filter=web

  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            .pnpm-store
            node_modules
            **/.next
            **/node_modules
            .turbo
          key: turbo-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('.github/workflows/*.yml') }}

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Generate Prisma client
        run: pnpm turbo run db:generate

      - name: Run database migrations
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: pnpm turbo run db:migrate

      - name: Build application
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          NEXT_PUBLIC_APP_ENV: production
        run: pnpm turbo run build --filter=web
