name: Deployment Application

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.12.3 --activate

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Set up PNPM global bin directory
        run: |
          export PNPM_HOME=$(pnpm prefix -g)/.pnpm-global
          export PATH=$PNPM_HOME/bin:$PATH

      - name: Install Vercel CLI
        run: pnpm install -g vercel

      - name: Pull Vercel Environment Info
        working-directory: apps/web
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: pnpm turbo run build --filter=web && vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --output-logs=errors-only

      - name: Deploy to Vercel
        working-directory: apps/web
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
