name: Deployment Application

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on: push

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            node_modules
            **/.next
            **/node_modules
            .turbo
          key: turbo-${{ hashFiles('yarn.lock') }}-deploy

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Install Vercel CLI
        run: yarn global add vercel

      - name: Pull Vercel Environment Info
        run: |
          vercel pull --yes --environment=production --token=${{secrets.VERCEL_TOKEN}} --cwd apps/web --scope ${{secrets.VERCEL_ORG_ID}}

      - name: Build and Deploy
        run: |
          yarn turbo run build --filter=web
          vercel build --prod --token=${{secrets.VERCEL_TOKEN}} --cwd apps/web
          vercel deploy --prebuilt --prod --token=${{secrets.VERCEL_TOKEN}} --cwd apps/web
