name: Deployment Application

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          echo "$HOME/.local/share/corepack/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --strict-peer-dependencies

      - name: Install Vercel CLI
        run: pnpm add -g vercel

      - name: Pull Vercel Environment Info
        working-directory: apps/web
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: pnpm turbo run build --filter=web && vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --output-logs=errors-only

      - name: Deploy to Vercel
        working-directory: apps/web
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
